import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import { MainLayout } from '@/components/MainLayout';
import { Box } from '@mui/system';

import { LinkStyle } from '@/components/NavMenu';
import {
  Title,
  TitleWeight,
  TitleH2,
  TitleDescription,
  EditBackground,
  PageBackground,
  Number,
  TitleBo,
  IndentationNext,
  Indentation,
} from '@/components/Title';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MainLayout title='Home'>
        <PageBackground>
          <Box
            sx={{
              display: 'flex',
              width: '100vw',
              alignItems: 'center',
              justifyContent: 'space-around',
              alignSelf: 'flex-start',
            }}
          >
            <Title>Hi Alex</Title>
            <Box
              sx={{
                display: 'flex',
                alignItems: 'center',
              }}
            >
              <EditBackground>
                <Title>Get started by editing&nbsp;</Title>
                <TitleWeight>src/pages/index.tsx</TitleWeight>
              </EditBackground>
            </Box>

            <LinkStyle
              href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
              target='_blank'
              rel='noopener noreferrer'
            >
              <Box
                sx={{
                  display: 'flex',
                }}
              >
                <Title>By </Title>
                <Image
                  src='/vercel.svg'
                  alt='Vercel Logo'
                  width={100}
                  height={24}
                  priority
                />
              </Box>
            </LinkStyle>
          </Box>
          <IndentationNext>
            <Image
              src='/next.svg'
              alt='Next.js Logo'
              width={180}
              height={37}
              priority
            />
            <Number>
              <Image
                src='/thirteen.svg'
                alt='13'
                width={31}
                height={40}
                priority
              />
            </Number>
          </IndentationNext>

          <Indentation>
            <TitleBo>
              <LinkStyle
                href='https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
                target='_blank'
                rel='noopener noreferrer'
              >
                <TitleH2>
                  Docs <span>-&gt;</span>
                </TitleH2>
                <TitleDescription>
                  Find in-depth information about Next.js features and&nbsp;API.
                </TitleDescription>
              </LinkStyle>
            </TitleBo>
            <TitleBo>
              <LinkStyle
                href='https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
                target='_blank'
                rel='noopener noreferrer'
                passHref
              >
                <TitleH2 sx={{ textDecoration: 'none' }}>
                  Learn <span>-&gt;</span>
                </TitleH2>
                <TitleDescription sx={{ textDecoration: 'none' }}>
                  Learn about Next.js in an interactive course
                  with&nbsp;quizzes!
                </TitleDescription>
              </LinkStyle>
            </TitleBo>
            <TitleBo>
              <LinkStyle
                href='https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
                target='_blank'
                rel='noopener noreferrer'
              >
                <TitleH2>
                  Templates <span>-&gt;</span>
                </TitleH2>
                <TitleDescription>
                  Discover and deploy boilerplate example Next.js&nbsp;projects.
                </TitleDescription>
              </LinkStyle>
            </TitleBo>
            <TitleBo>
              <LinkStyle
                href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
                target='_blank'
                rel='noopener noreferrer'
              >
                <TitleH2>
                  Deploy <span>-&gt;</span>
                </TitleH2>
                <TitleDescription>
                  Instantly deploy your Next.js site to a shareable URL
                  with&nbsp;Vercel.
                </TitleDescription>
              </LinkStyle>
            </TitleBo>
          </Indentation>
        </PageBackground>
      </MainLayout>
    </>
  );
}
